
# SnapGames 2018
# Basic Game Framework
#
language: java
jdk:
  - oraclejdk8
  - openjdk11

#sudo: false
script: mvn clean test install

# Improve build speed
cache:
  directories:
  - $HOME/.m2

# Define X11 env. for test execution
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
